[mcp_servers]

[mcp_servers.vibearound]
url = "http://127.0.0.1:12358/va/mcp?token=cb66b642fd8e74b59692d46cd44e19e8d78e6bbd023a3173fb2ab20cfa73db49"

[skills]

[[skills.config]]
path = "/Users/hexiguan/Project/NeoCraft/.codex/skills/vibearound"
enabled = true

[[skills.config]]
path = "/Users/hexiguan/Project/NeoCraft/.codex/skills/va-session"
enabled = true

[[skills.config]]
path = "/Users/hexiguan/Project/NeoCraft/.codex/skills/va-preview"
enabled = true

[[skills.config]]
path = "/Users/hexiguan/Project/NeoCraft/.codex/skills/va-md-preview"
enabled = true

[[skills.config]]
path = "/Users/hexiguan/Project/NeoCraft/.codex/skills/agent-collaboration"
enabled = true
