//! File system operations — config templates, properties parsing.

/// Generate a default `server.properties` content for a new instance.
pub fn default_server_properties(port: u16, motd: &str) -> String {
    format!(
        "#Minecraft server properties\n\
         #Generated by NeoCraft\n\
         server-port={port}\n\
         motd={motd}\n\
         enable-rcon=false\n\
         rcon.port={rcon_port}\n\
         rcon.password=\n\
         enable-query=false\n\
         query.port={query_port}\n\
         enable-jmx-monitoring=false\n",
        port = port,
        motd = motd,
        rcon_port = port + 10,
        query_port = port + 1,
    )
}

/// Generate `eula.txt` content with eula accepted.
pub fn eula_accepted() -> &'static str {
    "#EULA accepted automatically by NeoCraft\neula=true\n"
}
