//! File system operations — config templates, properties parsing.

use std::collections::HashMap;
use std::path::Path;
use tokio::io::{AsyncBufReadExt, BufReader};

/// Generate a default server.properties content for a new instance.
pub fn default_server_properties(port: u16, motd: &str) -> String {
    format!(
        r#"#Minecraft server properties — generated by NeoCraft
# ========== 网络与通信 ==========
server-port={port}
server-ip=
max-players=20
online-mode=true
enable-query=false
enable-rcon=false
rcon.port={rcon_port}
rcon.password=
# ========== 游戏玩法 ==========
gamemode=survival
difficulty=normal
allow-nether=true
allow-end=true
spawn-monsters=true
spawn-animals=true
spawn-npcs=true
pvp=true
force-gamemode=false
allow-flight=false
# ========== 世界生成与存储 ==========
level-name=world
level-seed=
generate-structures=true
max-world-size=29999984
level-type=minecraft:normal
generator-settings=
spawn-protection=16
# ========== 性能优化 ==========
view-distance=10
simulation-distance=10
entity-broadcast-range-percentage=100
max-tick-time=60000
network-compression-threshold=256
sync-chunk-writes=true
use-native-transport=true
# ========== 聊天与信息 ==========
motd={motd}
announce-advancements=true
enable-status=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
# ========== 管理 ==========
op-permission-level=4
function-permission-level=2
white-list=false
enforce-whitelist=false
# ========== 高级/安全 ==========
enforce-secure-profile=false
prevent-proxy-connections=false
resource-pack=
require-resource-pack=false
text-filtering-config=
snooper-enabled=false
"#,
        port = port,
        motd = motd,
        rcon_port = port + 10,
    )
}

/// Generate eula.txt content with eula accepted.
pub fn eula_accepted() -> &'static str {
    "#EULA accepted automatically by NeoCraft\neula=true\n"
}

/// Read a Java .properties file into a HashMap.
/// Preserves only key-value pairs; comments and blank lines are not stored.
pub async fn read_properties(path: &Path) -> Result<HashMap<String, String>, std::io::Error> {
    let file = tokio::fs::File::open(path).await?;
    let reader = BufReader::new(file);
    let mut lines = reader.lines();
    let mut props = HashMap::new();

    loop {
        let line = match lines.next_line().await {
            Ok(Some(l)) => l,
            Ok(None) => break,
            Err(e) => return Err(e),
        };
        let trimmed = line.trim();

        // Skip comments and blank lines
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with('!') {
            continue;
        }

        // Split on first = or :
        if let Some(pos) = trimmed.find(|c: char| c == '=' || c == ':') {
            let key = trimmed[..pos].trim().to_string();
            let value = trimmed[pos + 1..].trim().to_string();
            if !key.is_empty() {
                props.insert(key, value);
            }
        }
    }

    Ok(props)
}

/// Write a HashMap to a .properties file, preserving existing comments and structure.
/// Keys that exist in the file are updated in-place; new keys are appended.
pub async fn write_properties(path: &Path, props: &HashMap<String, String>) -> Result<(), std::io::Error> {
    // Read original file lines to preserve comments and ordering
    let original_lines: Vec<String> = if path.exists() {
        let content = tokio::fs::read_to_string(path).await?;
        content.lines().map(|s| s.to_string()).collect()
    } else {
        Vec::new()
    };

    let mut used_keys = std::collections::HashSet::new();
    let mut output = String::new();

    for line in &original_lines {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with('!') {
            // Preserve comments and blank lines as-is
            output.push_str(line);
            output.push('\n');
        } else if let Some(pos) = trimmed.find(|c: char| c == '=' || c == ':') {
            let key = trimmed[..pos].trim();
            if let Some(new_value) = props.get(key) {
                // Update existing key with new value
                output.push_str(&format!("{}={}\n", key, new_value));
                used_keys.insert(key.to_string());
            }
            // If key is not in props, omit it (supports deletion)
        } else {
            // Malformed line — preserve as-is
            output.push_str(line);
            output.push('\n');
        }
    }

    // Append new keys that weren't in the original file
    for (key, value) in props {
        if !used_keys.contains(key.as_str()) {
            output.push_str(&format!("{}={}\n", key, value));
        }
    }

    tokio::fs::write(path, output).await?;
    Ok(())
}
